#
# Module manifest for module 'MAUCacheAdmin'
#
# Generated by: Nick Ireland
#
# Generated on: 28/04/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'MAUCacheAdmin.psm1'

# Version number of this module.
ModuleVersion = '1.0.3'

# ID used to uniquely identify this module
GUID = '41ac64b9-6f2c-46a2-9d55-e6fb6c3d75ad'

# Author of this module
Author = 'Nick Ireland'


# Description of the functionality provided by this module
Description = 'Module for managing Microsoft AutoUpdate cache.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @("System.Net.Http")

}
